export const phrases = [
  "The Amazon rainforest,[a] also called Amazon jungle or Amazonia, is a moist broadleaf tropical rainforest in the",
  "in the Amazon biome that covers most of the Amazon basin of South America. This basin encompasses 7,000,000 km2",
  "(2,700,000 sq mi), of which 5,500,000 km2 (2,100,000 sq mi) are covered by the rainforest. This region includes",
  "includes territory belonging to nine nations and 3,344 formally acknowledged indigenous territories.",
  "The majority of the forest, 60%, is in Brazil, followed by Peru with 13%, Colombia with 10%, and with minor amounts in",
  'amounts in Bolivia, Ecuador, French Guiana, Guyana, Suriname, and Venezuela. Four nations have "Amazonas" as the',
  'as the name of one of their first-level administrative regions, and France uses the name "Guiana Amazonian Park" for',
  "Park\" for French Guiana's protected rainforest area. The Amazon represents over half of the planet's remaining",
  "remaining rainforests,[2] and comprises the largest and most biodiverse tract of tropical rainforest in the world,",
  "the world, with an estimated 390 billion individual trees in about 16,000 species.[3]",
  "More than 30 million people of 350 different ethnic groups live in the Amazon, which are subdivided into 9 different",
  "9 different national political systems and 3,344 formally acknowledged indigenous territories. Indigenous",
  "Indigenous peoples make up 9% of the total population, and 60 of the groups remain largely isolated.[4]",
  "Etymology",
  "The name Amazon is said to arise from a war Francisco de Orellana fought with the Tapuyas and other tribes. The women of",
  "The women of the tribe fought alongside the men, as was their custom.[5] Orellana derived the name Amazonas from the",
  "from the Amazons of Greek mythology, described by Herodotus and Diodorus.[5]",
  "History",
  "In the Amazonas, there has been fighting and wars between the neighboring tribes of the Jivaro. Several tribes of the",
  "of the Jivaroan group, including the Shuar, practised headhunting for trophies and headshrinking.[6] The accounts",
  "accounts of missionaries to the area in the borderlands between Brazil and Venezuela have recounted constant",
  "constant infighting in the Yanomami tribes. More than a third of the Yanomamo males, on average, died from",
  "died from warfare.[7]",
  "The Munduruku were a warlike tribe that expanded along the Tapajós river and its tributaries and were feared by",
  "feared by neighboring tribes. In the early 19th century, the Munduruku were pacified and subjugated by the",
  "by the Brazilians.[8]",
  "During the Amazon rubber boom it is estimated that diseases brought by immigrants, such as typhus and malaria, killed",
  "killed 40,000 native Amazonians.[9]",
  "In the 1950s, Brazilian explorer and defender of indigenous people, Cândido Rondon, supported the Villas-Bôas",
  "brothers' campaign, which faced strong opposition from the government and the ranchers of Mato Grosso and led to the",
  "led to the establishment of the first Brazilian National Park for indigenous people along the Xingu River in",
  "River in 1961.[10]",
  "In 1961, British explorer Richard Mason was killed by an uncontacted Amazon tribe known as the Panará.[11]",
  "The Matsés made their first permanent contact with the outside world in 1969. Before that date, they were effectively",
  "at-war with the Peruvian government.[12]",
  "Geography",
  "Location",
  "Nine countries share the Amazon basin—most of the rainforest, 58.4%, is contained within the borders of Brazil. The",
  "Brazil. The other eight countries include Peru with 12.8%, Bolivia with 7.7%, Colombia with 7.1%, Venezuela with",
  "with 6.1%, Guyana with 3.1%, Suriname with 2.5%, French Guiana with 1.4%, and Ecuador with 1%.[13]",
  "Natural\n\nAmazon rainforest in Colombia\n\nAerial view of the Amazon rainforest, near Manaus",
  "The rainforest likely formed during the Eocene era (from 56 million years to 33.9 million years ago). It appeared",
  "It appeared following a global reduction of tropical temperatures when the Atlantic Ocean had widened sufficiently",
  "to provide a warm, moist climate to the Amazon basin. The rainforest has been in existence for at least 55 million",
  "55 million years, and most of the region remained free of savanna-type biomes at least until the current ice age when",
  "ice age when the climate was drier and savanna more widespread.[14][15]",
  "Following the Cretaceous–Paleogene extinction event, the extinction of the dinosaurs and the wetter climate may",
  "climate may have allowed the tropical rainforest to spread out across the continent. From 66 to 34 Mya, the rainforest",
  "rainforest extended as far south as 45°. Climate fluctuations during the last 34 million years have allowed savanna",
  "savanna regions to expand into the tropics. During the Oligocene, for example, the rainforest spanned a relatively",
  "relatively narrow band. It expanded again during the Middle Miocene, then retracted to a mostly inland formation at",
  "at the last glacial maximum.[16] However, the rainforest still managed to thrive during these glacial periods,",
  "periods, allowing for the survival and evolution of a broad diversity of species.[17]",
  "Aerial view of the Amazon rainforest",
  "During the mid-Eocene, it is believed that the drainage basin of the Amazon was split along the middle of the continent",
  "continent by the Púrus Arch. Water on the eastern side flowed toward the Atlantic, while to the west water flowed",
  "flowed toward the Pacific across the Amazonas Basin. As the Andes Mountains rose, however, a large basin was created",
  "was created that enclosed a lake; now known as the Solimões Basin. Within the last 5–10 million years, this",
  "years, this accumulating water broke through the Púrus Arch, joining the easterly flow toward the",
  "toward the Atlantic.[18][19]",
  "There is evidence that there have been significant changes in the Amazon rainforest vegetation over the last 21,000",
  "last 21,000 years through the last glacial maximum (LGM) and subsequent deglaciation. Analyses of sediment",
  "of sediment deposits from Amazon basin paleolakes and the Amazon Fan indicate that rainfall in the basin during the",
  "during the LGM was lower than for the present, and this was almost certainly associated with reduced moist tropical",
  "tropical vegetation cover in the basin.[20] In present day, the Amazon receives approximately 9 feet of rainfall",
  "of rainfall annually. There is a debate, however, over how extensive this reduction was. Some scientists argue that",
  "argue that the rainforest was reduced to small, isolated refugia separated by open forest and grassland;[21] other",
  "other scientists argue that the rainforest remained largely intact but extended less far to the north, south, and",
  "south, and east than is seen today.[22] This debate has proved difficult to resolve because the practical",
  "practical limitations of working in the rainforest mean that data sampling is biased away from the center of the",
  "of the Amazon basin, and both explanations are reasonably well supported by the available data.",
  "Sahara Desert dust windblown to the Amazon",
  "More than 56% of the dust fertilizing the Amazon rainforest comes from the Bodélé depression in Northern Chad in the",
  "Chad in the Sahara desert. The dust contains phosphorus, important for plant growth. The yearly Sahara dust replaces",
  "replaces the equivalent amount of phosphorus washed away yearly in Amazon soil from rains and floods.[23]",
  "NASA's CALIPSO satellite has measured the amount of dust transported by wind from the Sahara to the Amazon: an average",
  "an average of 182 million tons of dust are windblown out of the Sahara each year, at 15 degrees west longitude, across",
  "across 2,600 km (1,600 mi) over the Atlantic Ocean (some dust falls into the Atlantic), then at 35 degrees West",
  "West longitude at the eastern coast of South America, 27.7 million tons (15%) of dust fall over the Amazon basin (22",
  "basin (22 million tons of it consisting of phosphorus), 132 million tons of dust remain in the air, 43 million tons of",
  "tons of dust are windblown and falls on the Caribbean Sea, past 75 degrees west longitude.[24]",
  "CALIPSO uses a laser range finder to scan the Earth's atmosphere for the vertical distribution of dust and other",
  "and other aerosols. CALIPSO regularly tracks the Sahara-Amazon dust plume. CALIPSO has measured variations in the",
  "in the dust amounts transported – an 86 percent drop between the highest amount of dust transported in 2007 and the",
  "2007 and the lowest in 2011.",
  "A possibility causing the variation is the Sahel, a strip of semi-arid land on the southern border of the Sahara. When",
  "When rain amounts in the Sahel are higher, the volume of dust is lower. The higher rainfall could make more vegetation",
  "vegetation grow in the Sahel, leaving less sand exposed to winds to blow away.[25]",
  "Amazon phosphorus also comes as smoke due to biomass burning in Africa.[26][27]\n\nHuman activity",
  "Manaus, with 2.2 million inhabitants, is the largest city in the Amazon basin",
  "The Yanomami are a group of approximately 32,000 indigenous people who live in the Amazon rainforest.[28]",
  "Based on archaeological evidence from an excavation at Caverna da Pedra Pintada, human inhabitants first settled in",
  "settled in the Amazon region at least 11,200 years ago.[29] Subsequent development led to late-prehistoric",
  "settlements along the periphery of the forest by AD 1250, which induced alterations in the forest cover.[30]",
  "For a long time, it was thought that the Amazon rainforest was never more than sparsely populated, as it was impossible",
  "impossible to sustain a large population through agriculture given the poor soil. Archeologist Betty Meggers was a",
  "was a prominent proponent of this idea, as described in her book Amazonia: Man and Culture in a Counterfeit Paradise.",
  "Paradise. She claimed that a population density of 0.2 inhabitants per square kilometre (0.52/sq mi) is the maximum",
  "the maximum that can be sustained in the rainforest through hunting, with agriculture needed to host a larger",
  "a larger population.[31] However, recent anthropological findings have suggested that the region was actually",
  "actually densely populated. Some 5 million people may have lived in the Amazon region in AD 1500, divided between",
  "between dense coastal settlements, such as that at Marajó, and inland dwellers.[32] By 1900, the population had",
  "had fallen to 1 million and by the early 1980s it was less than 200,000.[32]",
  "The first European to travel the length of the Amazon River was Francisco de Orellana in 1542.[33] The BBC's Unnatural",
  "Unnatural Histories presents evidence that Orellana, rather than exaggerating his claims as previously thought,",
  "thought, was correct in his observations that a complex civilization was flourishing along the Amazon in the 1540s.",
  "the 1540s. It is believed that civilization was later devastated by the spread of diseases from Europe, such as",
  "such as smallpox.[34] This civilization was investigated by the British explorer Percy Fawcett in the early",
  "in the early twentieth century. The results of his expeditions were inconclusive and he disappeared mysteriously on",
  "on his last trip. His name for this lost civilization was the City of Z.",
  "Since the 1970s, numerous geoglyphs have been discovered on deforested land dating between AD 1–1250, furthering",
  "furthering claims about Pre-Columbian civilizations.[35][36] Ondemar Dias is accredited with first discovering",
  "the geoglyphs in 1977, and Alceu Ranzi is credited with furthering their discovery after flying over Acre.[34][37]",
  "The BBC's Unnatural Histories presented evidence that the Amazon rainforest, rather than being a pristine",
  "a pristine wilderness, has been shaped by man for at least 11,000 years through practices such as forest gardening and",
  "and terra preta.[34] Terra preta is found over large areas in the Amazon forest; and is now widely accepted as a product",
  "as a product of indigenous soil management. The development of this fertile soil allowed agriculture and",
  "and silviculture in the previously hostile environment; meaning that large portions of the Amazon rainforest are",
  "are probably the result of centuries of human management, rather than naturally occurring as has previously been",
  "been supposed.[38] In the region of the Xingu tribe, remains of some of these large settlements in the middle of the",
  "of the Amazon forest were found in 2003 by Michael Heckenberger and colleagues of the University of Florida. Among",
  "Among those were evidence of roads, bridges and large plazas.[39]",
  "Biodiversity, flora and fauna",
  "Deforestation in the Amazon rainforest threatens many species of tree frogs, which are very sensitive to",
  "to environmental changes (pictured: giant leaf frog)",
  "A giant, bundled liana in western Brazil",
  "Wet tropical forests are the most species-rich biome, and tropical forests in the Americas are consistently more",
  "more species rich than the wet forests in Africa and Asia.[40] As the largest tract of tropical rainforest in the",
  "in the Americas, the Amazonian rainforests have unparalleled biodiversity. One in ten known species in the world",
  "in the world lives in the Amazon rainforest.[41] This constitutes the largest collection of living plants and animal",
  "and animal species in the world.",
  "The region is home to about 2.5 million insect species,[42] tens of thousands of plants, and some 2,000 birds and",
  "birds and mammals. To date, at least 40,000 plant species,[43] 2,200 fishes,[44] 1,294 birds, 427 mammals, 428",
  "428 amphibians, and 378 reptiles have been scientifically classified in the region.[45] One in five of all bird",
  "of all bird species are found in the Amazon rainforest, and one in five of the fish species live in Amazonian rivers and",
  "rivers and streams. Scientists have described between 96,660 and 128,843 invertebrate species in Brazil",
  "in Brazil alone.[46]",
  "The biodiversity of plant species is the highest on Earth with one 2001 study finding a quarter square kilometer (62",
  "(62 acres) of Ecuadorian rainforest supports more than 1,100 tree species.[47] A study in 1999 found one square",
  "one square kilometer (247 acres) of Amazon rainforest can contain about 90,790 tonnes of living plants. The average",
  "The average plant biomass is estimated at 356 ± 47 tonnes per hectare.[48] To date, an estimated 438,000 species of",
  "species of plants of economic and social interest have been registered in the region with many more remaining to be",
  "to be discovered or catalogued.[49] The total number of tree species in the region is estimated at 16,000.[3]",
  "The green leaf area of plants and trees in the rainforest varies by about 25% as a result of seasonal changes. Leaves",
  "Leaves expand during the dry season when sunlight is at a maximum, then undergo abscission in the cloudy wet season.",
  "wet season. These changes provide a balance of carbon between photosynthesis and respiration.[50]",
  "The rainforest contains several species that can pose a hazard. Among the largest predatory creatures are the black",
  "the black caiman, jaguar, cougar, and anaconda. In the river, electric eels can produce an electric shock that can",
  "that can stun or kill, while piranha are known to bite and injure humans.[51] Various species of poison dart frogs",
  "dart frogs secrete lipophilic alkaloid toxins through their flesh. There are also numerous parasites and disease",
  "and disease vectors. Vampire bats dwell in the rainforest and can spread the rabies virus.[52] Malaria, yellow fever",
  "fever and dengue fever can also be contracted in the Amazon region.",
  "The biodiversity in the Amazon is becoming increasingly threatened, primarily by habitat loss from deforestation",
  "as well as increased frequency of fires. Over 90% of Amazonian plant and vertebrate species (13,000-14,000 in total)",
  "in total) may have been impacted to some degree by fires.[53]",
  "Pipa pipa, a species of frog found within the Amazon.\n\nDeforestation",
  "Timelapse of the deforestation 1984–2018 (bottom right)",
  "Deforestation in the Maranhão state of Brazil, 2016",
  "Home to much of the Amazon rainforest, Brazil's tropical primary (old-growth) forest loss greatly exceeds that of",
  "that of other countries.[54]",
  'Overall, 20% of the Amazon rainforest has been "transformed" (deforested) and another 6% has been "highly',
  '"highly degraded", causing Amazon Watch to warn that the Amazonia is in the midst of a tipping point crisis.[55]',
  "Deforestation is the conversion of forested areas to non-forested areas. The main sources of deforestation in the",
  "in the Amazon are human settlement and the development of the land.[56] In 2018, about 17% of the Amazon rainforest was",
  "was already destroyed. Research suggests that upon reaching about 20–25% (hence 3–8% more), the tipping point to",
  "point to flip it into a non-forest ecosystem – degraded savannah – (in eastern, southern and central Amazonia) will be",
  "will be reached.[57][58]",
  "Prior to the early 1960s, access to the forest's interior was highly restricted, and the forest remained basically",
  "basically intact.[59] Farms established during the 1960s were based on crop cultivation and the slash and burn",
  "and burn method. However, the colonists were unable to manage their fields and the crops because of the loss of soil",
  "loss of soil fertility and weed invasion.[60] The soils in the Amazon are productive for just a short period of time, so",
  "of time, so farmers are constantly moving to new areas and clearing more land.[60] These farming practices led to",
  "led to deforestation and caused extensive environmental damage.[61] Deforestation is considerable, and areas",
  "and areas cleared of forest are visible to the naked eye from outer space.",
  "In the 1970s, construction began on the Trans-Amazonian highway. This highway represented a major threat to the",
  "to the Amazon rainforest.[62] The highway still has not been completed, limiting the environmental damage.",
  "Between 1991 and 2000, the total area of forest lost in the Amazon rose from 415,000 to 587,000 km2 (160,000 to",
  "(160,000 to 227,000 sq mi), with most of the lost forest becoming pasture for cattle.[63] Seventy percent of",
  "percent of formerly forested land in the Amazon, and 91% of land deforested since 1970, have been used for livestock",
  "livestock pasture.[64][65] Currently, Brazil is the largest global producer of soybeans. New research however,",
  "however, conducted by Leydimere Oliveira et al., has shown that the more rainforest is logged in the Amazon, the less",
  "the less precipitation reaches the area and so the lower the yield per hectare becomes. So despite the popular",
  "the popular perception, there has been no economical advantage for Brazil from logging rainforest zones and",
  "zones and converting these to pastoral fields.[66]",
  "The needs of soy farmers have been used to justify many of the controversial transportation projects that are",
  "that are currently developing in the Amazon. The first two highways successfully opened up the rainforest and led to",
  "and led to increased settlement and deforestation. The mean annual deforestation rate from 2000 to 2005 (22,392 km2",
  "or 8,646 sq mi per year) was 18% higher than in the previous five years (19,018 km2 or 7,343 sq mi per year).[67]",
  "year).[67] Although deforestation declined significantly in the Brazilian Amazon between 2004 and 2014, there has",
  "there has been an increase to the present day.[68]",
  "Brazilian mining operation in the Amazon Rainforest.",
  "Brazil's President, Jair Bolsonaro, has supported the relaxation of regulations placed on agricultural land. He",
  "land. He has used his time in office to allow for more deforestation and more exploitation of the Amazon's rich natural",
  "natural resources.",
  "Since the discovery of fossil fuel reservoirs in the Amazon rainforest, oil drilling activity has steadily",
  "steadily increased, peaking in the Western Amazon in the 1970s and ushering another drilling boom in the 2000s.[69]",
  "2000s.[69] Oil companies have to set up their operations by opening new roads through the forests, which often",
  "which often contributes to deforestation in the region.[70]",
  "The European Union–Mercosur free trade agreement, which would form one of the world's largest free trade areas, has",
  "areas, has been denounced by environmental activists and indigenous rights campaigners.[71] The fear is that the",
  "is that the deal could lead to more deforestation of the Amazon rainforest as it expands market access to Brazilian",
  "Brazilian beef.[72]",
  "According to a November 2021 report by Brazil's INPE, based on satellite data, deforestation has increased by 22%",
  "by 22% over 2020 and is at its highest level since 2006.[73][74]",
  "2019 fires",
  "There have been 72,843 fires in Brazil in 2019, with more than half within the Amazon region.[75][76][77] In August",
  "In August 2019 there were a record number of fires.[78] Deforestation in the Brazilian Amazon rose more than 88% in",
  "than 88% in June 2019 compared with the same month in 2018.[79]",
  "NASA satellite observation of deforestation in the Mato Grosso state of Brazil. The transformation from forest to",
  "forest to farm is evident by the paler square shaped areas under development.",
  "Fires and deforestation in the state of Rondônia",
  "One consequence of forest clearing in the Amazon: thick smoke that hangs over the forest",
  "Impact of deforestation on natural habitat of trees",
  "The increased area of fire-impacted forest coincided with a relaxation of environmental regulations from the",
  "from the Brazilian government. Notably, before those regulations were put in place in 2008 the fire-impacted area",
  "area was also larger compared to the regulation period of 2009–2018. As these fire continue to move closer to the heart",
  "to the heart of the Amazon Basin, their impact on biodiversity will only increase in scale, as the cumulative",
  "cumulative fire-impacted area is correlated with the number of species impacted.[53]",
  "Conservation and climate change",
  "Environmentalists are concerned about loss of biodiversity that will result from destruction of the forest, and",
  "forest, and also about the release of the carbon contained within the vegetation, which could accelerate global",
  "global warming. Amazonian evergreen forests account for about 10% of the world's terrestrial primary productivity",
  "and 10% of the carbon stores in ecosystems[80] – of the order of 1.1 × 1011 metric tonnes of carbon.[81] Amazonian",
  "Amazonian forests are estimated to have accumulated 0.62 ± 0.37 tons of carbon per hectare per year between 1975 and",
  "1975 and 1996.[81] In 2021 it was reported that the Amazon for the first time emitted more greenhouse gases than it",
  "than it absorbed.[82] Though often referenced as producing more than a quarter of the Earth's oxygen, this often",
  "this often stated, but misused statistic actually refers to oxygen turnover. The net contribution of the ecosystem",
  "ecosystem is approximately zero.[83]",
  "One computer model of future climate change caused by greenhouse gas emissions shows that the Amazon rainforest",
  "rainforest could become unsustainable under conditions of severely reduced rainfall and increased temperatures,",
  "leading to an almost complete loss of rainforest cover in the basin by 2100.[84][85], and severe economic, natural",
  "natural capital and ecosystem services impacts of not averting the tipping point.[86] However, simulations of",
  "of Amazon basin climate change across many different models are not consistent in their estimation of any rainfall",
  "rainfall response, ranging from weak increases to strong decreases.[87] The result indicates that the rainforest",
  "rainforest could be threatened through the 21st century by climate change in addition to deforestation.",
  "In 1989, environmentalist C.M. Peters and two colleagues stated there is economic as well as biological incentive to",
  "to protecting the rainforest. One hectare in the Peruvian Amazon has been calculated to have a value of $6820 if intact",
  "if intact forest is sustainably harvested for fruits, latex, and timber; $1000 if clear-cut for commercial timber",
  "timber (not sustainably harvested); or $148 if used as cattle pasture.[88]",
  "According to WWF, ecotourism could help the Amazon to reduce deforestation and climate change. Ecotourism is",
  "is currently still little practiced in the Amazon, partly due to lack of information about places where",
  "where implementation is possible. Ecotourism is a sector that can also be taken up by the Indigenous community in the",
  "in the Amazon as a source of income and revenue. An ecotourism project in the Brazilian-section of the Amazon",
  "the Amazon rainforest had been under consideration by Brazil's State Secretary for the Environment and Sustainable",
  "Development in 2009, along the Aripuanã river, in the Aripuanã Sustainable Development Reserve.[89] Also, some",
  "Also, some community-based ecotourism exists in the Mamirauá Sustainable Development Reserve.[90] Ecotourism is",
  "is also practiced in the Peruvian-section of the Amazon rainforest. A few ecolodges are for instance present between",
  "between Cusco and Madre de Dios.[91]",
  "As indigenous territories continue to be destroyed by deforestation and ecocide, such as in the Peruvian Amazon[92]",
  "Amazon[92] indigenous peoples' rainforest communities continue to disappear, while others, like the Urarina",
  "the Urarina continue to struggle to fight for their cultural survival and the fate of their forested territories.",
  "Meanwhile, the relationship between non-human primates in the subsistence and symbolism of indigenous lowland",
  "lowland South American peoples has gained increased attention, as have ethno-biology and community-based",
  "conservation efforts.",
  "From 2002 to 2006, the conserved land in the Amazon rainforest almost tripled and deforestation rates dropped up to",
  "up to 60%. About 1,000,000 km2 (250,000,000 acres) have been put onto some sort of conservation, which adds up to a",
  "adds up to a current amount of 1,730,000 km2 (430,000,000 acres).[93]",
  "In April 2019, the Ecuadorian court stopped oil exploration activities in 180,000 hectares (440,000 acres) of the",
  "of the Amazon rainforest.[94]",
  "In July 2019, the Ecuadorian court forbade the government to sell territory with forests to oil companies.[95]",
  "In September 2019, the US and Brazil agreed to promote private-sector development in the Amazon. They also pledged a",
  "pledged a $100m biodiversity conservation fund for the Amazon led by the private sector. Brazil's foreign minister",
  "minister stated that opening the rainforest to economic development was the only way to protect it.[96]",
  "Anthropogenic emission of greenhouse gases broken down by sector for the year 2000.",
  "Aerosols over the Amazon each September for four burning seasons (2005 through 2008). The aerosol scale (yellow to",
  "(yellow to dark reddish-brown) indicates the relative amount of particles that absorb sunlight.",
  "Aerial roots of red mangrove on an Amazonian river.",
  "Climate change disturbances of rainforests.[97]",
  "A 2009 study found that a 4 °C rise (above pre-industrial levels) in global temperatures by 2100 would kill 85% of the",
  "85% of the Amazon rainforest while a temperature rise of 3 °C would kill some 75% of the Amazon.[98]",
  "A new study by an international team of environmental scientists in the Brazilian Amazon shows that protection of",
  "of freshwater biodiversity can be increased by up to 600% through integrated freshwater-terrestrial planning",
  "planning .[99]",
  "Deforestation in the Amazon rainforest region has a negative impact on local climate.[100] It was one of the main",
  "of the main causes of the severe drought of 2014–2015 in Brazil.[101][102] This is because the moisture from the",
  "from the forests is important to the rainfall in Brazil, Paraguay and Argentina. Half of the rainfall in the Amazon",
  "the Amazon area is produced by the forests.[103]",
  "Results of a 2021 scientific synthesis indicate that, in terms of global warming, the Amazon basin with the Amazon",
  "the Amazon rainforest is currently emitting more greenhouse gases than it absorbs overall. Climate change impacts",
  "impacts and human activities in the area – mainly wildfires, current land-use and deforestation – are causing a",
  "causing a release of forcing agents that likely result in a net warming effect.[104][97][105]",
  'In 2022 the supreme court of Ecuador decided that "“under no circumstances can a project be carried out that generates',
  "generates excessive sacrifices to the collective rights of communities and nature.” It also required the",
  "the government to respect the opinion of Indigenous peoples of the Americas about different industrial projects on",
  "projects on their land. Advocates of the decision argue that it will have consequences far beyond Ecuador. In",
  "Ecuador. In general, ecosystems are in better shape when indigenous peoples own or manage the land.[106]",
  "Remote sensing",
  'This image reveals how the forest and the atmosphere interact to create a uniform layer of "popcorn-shaped" cumulus',
  "cumulus clouds.",
  "The use of remotely sensed data is dramatically improving conservationists' knowledge of the Amazon basin. Given",
  "Given the objectivity and lowered costs of satellite-based land cover and -change analysis, it appears likely that",
  "likely that remote sensing technology will be an integral part of assessing the extents, locations and damage of",
  "damage of deforestation in the basin.[107] Furthermore, remote sensing is the best and perhaps only possible way to",
  "way to study the Amazon on a large scale.[108]",
  "The use of remote sensing for the conservation of the Amazon is also being used by the indigenous tribes of the basin to",
  "the basin to protect their tribal lands from commercial interests. Using handheld GPS devices and programs like",
  "like Google Earth, members of the Trio Tribe, who live in the rainforests of southern Suriname, map out their",
  "out their ancestral lands to help strengthen their territorial claims.[109] Currently, most tribes in the Amazon do",
  "Amazon do not have clearly defined boundaries, making it easier for commercial ventures to target their",
  "their territories.",
  "To accurately map the Amazon's biomass and subsequent carbon-related emissions, the classification of tree growth",
  "tree growth stages within different parts of the forest is crucial. In 2006, Tatiana Kuplich organized the trees of",
  "the trees of the Amazon into four categories: mature forest, regenerating forest [less than three years],",
  "years], regenerating forest [between three and five years of regrowth], and regenerating forest [eleven to",
  "[eleven to eighteen years of continued development].[110] The researcher used a combination of synthetic aperture",
  "aperture radar (SAR) and Thematic Mapper (TM) to accurately place the different portions of the Amazon into one of the",
  "one of the four classifications.",
  "Impact of early 21st-century Amazon droughts",
  "In 2005, parts of the Amazon basin experienced the worst drought in one hundred years,[111] and there were",
  "there were indications that 2006 may have been a second successive year of drought.[112] A 2006 article in the UK",
  "in the UK newspaper The Independent reported the Woods Hole Research Center results, showing that the forest in its",
  "in its present form could survive only three years of drought.[113][114] Scientists at the Brazilian National",
  "National Institute of Amazonian Research argued in the article that this drought response, coupled with the effects",
  'the effects of deforestation on regional climate, are pushing the rainforest towards a "tipping point" where it',
  "where it would irreversibly start to die.[115] It concluded that the forest is on the brink of[vague] being turned",
  "turned into savanna or desert, with catastrophic consequences for the world's climate.[citation needed] A study",
  "A study published in Nature Communications in October 2020 found that about 40% of the Amazon rainforest is at risk of",
  "is at risk of becoming a savanna-like ecosystem due to reduced rainfall.[116] A study published in Nature climate",
  "climate change provided direct empirical evidence that more than three-quarters of the Amazon rainforest has been",
  "has been losing resilience since the early 2000s, risking dieback with profound implications for biodiversity,",
  "carbon storage and climate change at a global scale.[117]",
  "According to the World Wide Fund for Nature, the combination of climate change and deforestation increases the",
  "the drying effect of dead trees that fuels forest fires.[118]",
  "In 2010, the Amazon rainforest experienced another severe drought, in some ways more extreme than the 2005 drought.",
  "drought. The affected region was approximately 3,000,000 km2 (1,160,000 sq mi) of rainforest, compared with",
  "with 1,900,000 km2 (734,000 sq mi) in 2005. The 2010 drought had three epicenters where vegetation died off,",
  "died off, whereas in 2005, the drought was focused on the southwestern part. The findings were published in the",
  "in the journal Science. In a typical year, the Amazon absorbs 1.5 gigatons of carbon dioxide; during 2005 instead 5",
  "instead 5 gigatons were released and in 2010 8 gigatons were released.[119][120] Additional severe droughts",
  "droughts occurred in 2010, 2015, and 2016.[121]",
  "In 2019 Brazil's protections of the Amazon rainforest were slashed, resulting in a severe loss of trees.[122]",
  "According to Brazil's National Institute for Space Research (INPE), deforestation in the Brazilian Amazon rose",
  "Amazon rose more than 50% in the first three months of 2020 compared to the same three-month period in 2019.[123]",
  "In 2020, a 17 percent rise was noted in the Amazon wildfires, marking the worst start to the fire season in a decade. The",
  "decade. The first 10 days of August 2020 witnessed 10,136 fires. An analysis of the government figures reflected 81",
  "81 per cent increase in fires in federal reserves, in comparison with the same period in 2019.[124] However,",
  'However, President Jair Bolsonaro turned down the existence of fires, calling it a "lie", despite the data produced',
  "produced by his own government.[125] Satellites in September recorded 32,017 hotspots in the world's largest",
  "largest rainforest, a 61% rise from the same month in 2019.[126] In addition, October saw a huge surge in the number of",
  "number of hotspots in the forest (more than 17,000 fires are burning in the Amazon's rainforest) - with more than",
  "more than double the amount detected in the same month last year.[127]",
];
